### ISSUE TITLE
Pingdom module

### ISSUE THREAD

**Issue by jvehent** [mozilla-services/userplex#4]
Not sure if the [API](https://www.pingdom.com/resources/api) can manage users.

**Comment by oremj** [comment]
I e-mailed support. Their response, "No I'm afraid it is not possible to delete or invite Users via the API at the moment, but it might be possible in the future".

Shall we close this one?

**Comment by jvehent** [comment]
I don't mind keeping issues open for tracking purpose. We should keep asking pingdom monthly until they add the feature. I'll write a script :smiling_imp:
