### ISSUE TITLE
Better handling of partial failures in user creations

### ISSUE THREAD

**Issue by jvehent** [mozilla-services/userplex#45]
@ckolos was creating an aws user today and userplex failed to upload the user's ssh key. Since this step is executed towards the end of the user creation process, the end state was somewhat inconsistent: user wasn't fully setup, did not get a notification, but subsequent runs of userplex didn't finish the work because the user existed.

I'm wondering how to deal with those issues. Should we notify the user with a message saying "these 3 steps failed, please fix manually", or should we rollback user creation entirely when a step fails? I imagine the latter would be cleaner, but realistically most users can fix their own issues...

**Comment by ckolos** [comment]
I believe this also happens if the key contained in the user record isn't in openssh format (ala Putty keys)
