### ISSUE TITLE
Improve logging architecture.

### ISSUE THREAD

**Issue by jvehent** [mozilla-services/userplex#9]
Each module currently logs opportunistically using Go's `log` module. `userplex` should have a single pipe for logging that enforces the log format and writes to a location controlled by the main configuration.

One idea would be to pass a logging channel to each module that is consumed by the main program, and writes to stdout, a file, or syslog. Modules should not have to know much about the way logging is setup, they should just call some `modules.Log(level int, format string, variables ...interface{})` function.

**Comment by oremj** [comment]
https://github.com/Sirupsen/logrus is a pretty good library, which includes log levels. It's also used in some pretty large projects. Only downside is, no line numbers in the log output.

**Comment by jvehent** [comment]
I've never used logrus before, but it looks really nice! I would be useful to log the name of the module as an additional field. Ideally, the modules wouldn't know about logrus, and just log to a channel provided via a configuration.

**Comment by jvehent** [comment]
This has been implemented.
